### PR TITLE
Added Persian translation

### PR DESCRIPTION
**Pull request by ShayanTheNerd**
#103 @hail2u
The Persian translation is finished!

### CODE REVIEW

**Comment by hail2u** [comment]
Thanks, translation looks good. However, if you use Prettier, please disable it. I don’t use Prettier for this repository.

**Comment by ShayanTheNerd** [comment]
> Thanks, translation looks good. However, if you use Prettier, please disable it. I don’t use Prettier for this repository.
You're welcome.
No I did not use Prettier for the fork clone either. Also, GitHub says there are no conflicts, so I think we're good to go.

**Comment by hail2u** [comment]
If you don’t use Prettier, why you delete empty lines? And why re-format some Japanese and Chinese text? I don’t accept these changes. Please check **ALL** diff.

**Comment by ShayanTheNerd** [comment]
> If you don’t use Prettier, why you delete empty lines? And why re-format some Japanese and Chinese text? I don’t accept these changes. Please check **ALL** diff.

You're right, my bad, I thought diffs were caused by something else.
Anyway, It's all fixed now.

**Comment by hail2u** [comment]
Thanks, merged.

**Pull request merged**
